### ISSUE TITLE
Grafana pre-populated dashboards not working

### ISSUE THREAD

**Issue by apaskulin** [sensu/sandbox#25] opened 2018-09-27 00:21 UTC
Doing a run through of the Core sandbox, I was unable to get data to appear in Grafana using the links pre-created during setup. The data is available in Grafana if you create a new dashboard, but the pre-populated links should work. Here's the line where they're created during setup: https://github.com/sensu/sandbox/blob/master/sensu/provision/setup.sh#L179

**Comment by jspaleta** [comment] 2018-10-09 22:27
Found the issue.  Hostname as set in the Vagrantfile is sensu-sandbox. Testing a fix now

**Comment by jspaleta** [comment] 2018-10-10 05:51
Okay pushed a fix to ensure the hostname is set for core/enterprise provisioning.
Closing now as the issue is resolved.

**Closed by jspaleta** 2018-10-10 05:51 UTC
